name: pulling_manager
description: "PullingManager"
homepage: https://github.com/droididan/pulling_manager


version: 0.1.6

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true
